"""Shared data models."""

from arena_auto.models.config import (
    AdbConfig,
    AppConfig,
    ArenaProfile,
    AutomationSettings,
    BattleSettings,
    ButtonGeometry,
    CalibrationSettings,
    CalibrationWeights,
    DebugSettings,
    OpponentConfig,
    OcrSettings,
    PaddingSettings,
    PurchaseSettings,
    RecognitionSettings,
    RecoverySettings,
    ResultSettings,
    ScreenSettings,
    TemplateEntry,
    TimeoutSettings,
)
from arena_auto.models.recognition import (
    ChallengeCount,
    DetectionResult,
    OCRBox,
    Opponent,
    Point,
    Region,
)
from arena_auto.models.state import AutomationState, ScreenKind, SessionStatistics

__all__ = [
    "AdbConfig",
    "AppConfig",
    "ArenaProfile",
    "AutomationSettings",
    "AutomationState",
    "BattleSettings",
    "ButtonGeometry",
    "CalibrationSettings",
    "CalibrationWeights",
    "ChallengeCount",
    "DebugSettings",
    "DetectionResult",
    "OCRBox",
    "Opponent",
    "OpponentConfig",
    "OcrSettings",
    "PaddingSettings",
    "Point",
    "PurchaseSettings",
    "RecognitionSettings",
    "RecoverySettings",
    "Region",
    "ResultSettings",
    "ScreenKind",
    "ScreenSettings",
    "SessionStatistics",
    "TemplateEntry",
    "TimeoutSettings",
]
